import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const bridge = await readFile(new URL('../mobile/native-bridge.js', import.meta.url), 'utf8')
const build = await readFile(new URL('../scripts/build-mobile.mjs', import.meta.url), 'utf8')
const androidBuild = await readFile(new URL('../android/app/build.gradle', import.meta.url), 'utf8')
const windowsBuild = await readFile(new URL('../scripts/build-android.ps1', import.meta.url), 'utf8')
const assetBuild = await readFile(new URL('../scripts/generate-native-assets.ps1', import.meta.url), 'utf8')
const iosPackage = await readFile(new URL('../ios/App/CapApp-SPM/Package.swift', import.meta.url), 'utf8')
const iosIcon = await readFile(new URL('../ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png', import.meta.url))
const mobileUi = await readFile(new URL('../static/index.html', import.meta.url), 'utf8')
const appDelegate = await readFile(new URL('../ios/App/App/AppDelegate.swift', import.meta.url), 'utf8')
const config = JSON.parse(await readFile(new URL('../capacitor.config.json', import.meta.url), 'utf8'))

assert.match(build, /UPLINK_API_ORIGIN/)
assert.match(build, /parsedOrigin\.protocol !== 'https:'/)
assert.match(build, /UPLINK_RELEASE_BUILD/)
assert.match(build, /example\\\.\(com\|org\|net\)/)
assert.match(build, /parsedOrigin\.origin !== apiOrigin/)
assert.match(build, /endsWith\('\.invalid'\)/)
assert.doesNotMatch(config.server ? JSON.stringify(config.server) : '', /"url"/)
assert.equal(config.loggingBehavior, 'none')
assert.match(bridge, /SecureStorage/)
assert.match(bridge, /api\/account\/ws-ticket/)
assert.match(bridge, /encodeURIComponent\(payload\.ticket\)/)
assert.doesNotMatch(bridge, /MINIMAX_API_KEY|DEEPSEEK_API_KEY|XF_APIKEY|DOUBAO_ACCESS_TOKEN/)
assert.match(androidBuild, /UPLINK_ANDROID_VERSION_CODE/)
assert.match(androidBuild, /UPLINK_REQUIRE_ANDROID_SIGNING/)
assert.match(windowsBuild, /verify-android-package\.ps1/)
assert.doesNotMatch(windowsBuild, /MINIMAX_API_KEY|DEEPSEEK_API_KEY|XF_APIKEY|DOUBAO_ACCESS_TOKEN/)
assert.match(assetBuild, /AppIcon-512@2x\.png/)
assert.match(assetBuild, /DarkBackground/)
assert.match(iosPackage, /path: "\.\.\/\.\.\/\.\.\/node_modules\/@aparajita\/capacitor-secure-storage"/)
assert.equal(iosIcon.readUInt32BE(16), 1024)
assert.equal(iosIcon.readUInt32BE(20), 1024)
assert.equal(iosIcon[25], 2, 'App Store icon must be an RGB PNG without alpha')
assert.match(mobileUi, /\.hud-line\{left:50%;bottom:52%/)
assert.match(mobileUi, /\.hud-line\{bottom:54%;font-size:18px\}/)
assert.match(mobileUi, /window\.UplinkNative&&window\.UplinkNative\.isNative\?1\.65:1/)
assert.match(appDelegate, /setCategory\(\.playAndRecord,/)
assert.match(appDelegate, /mode: \.voiceChat/)
assert.match(appDelegate, /\.defaultToSpeaker/)
assert.match(appDelegate, /overrideOutputAudioPort\(\.speaker\)/)

console.log('native mobile build contract tests passed')
