import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const bridge = await readFile(new URL('../mobile/native-bridge.js', import.meta.url), 'utf8')
const build = await readFile(new URL('../scripts/build-mobile.mjs', import.meta.url), 'utf8')
const androidBuild = await readFile(new URL('../android/app/build.gradle', import.meta.url), 'utf8')
const windowsBuild = await readFile(new URL('../scripts/build-android.ps1', import.meta.url), 'utf8')
const assetBuild = await readFile(new URL('../scripts/generate-native-assets.ps1', import.meta.url), 'utf8')
const config = JSON.parse(await readFile(new URL('../capacitor.config.json', import.meta.url), 'utf8'))

assert.match(build, /UPLINK_API_ORIGIN/)
assert.match(build, /parsedOrigin\.protocol !== 'https:'/)
assert.match(build, /UPLINK_RELEASE_BUILD/)
assert.match(build, /example\\\.\(com\|org\|net\)/)
assert.match(build, /parsedOrigin\.origin !== apiOrigin/)
assert.match(build, /endsWith\('\.invalid'\)/)
assert.doesNotMatch(config.server ? JSON.stringify(config.server) : '', /"url"/)
assert.equal(config.loggingBehavior, 'none')
assert.match(bridge, /SecureStorage/)
assert.match(bridge, /api\/account\/ws-ticket/)
assert.match(bridge, /encodeURIComponent\(payload\.ticket\)/)
assert.doesNotMatch(bridge, /MINIMAX_API_KEY|XF_APIKEY|DOUBAO_ACCESS_TOKEN/)
assert.match(androidBuild, /UPLINK_ANDROID_VERSION_CODE/)
assert.match(androidBuild, /UPLINK_REQUIRE_ANDROID_SIGNING/)
assert.match(windowsBuild, /verify-android-package\.ps1/)
assert.doesNotMatch(windowsBuild, /MINIMAX_API_KEY|XF_APIKEY|DOUBAO_ACCESS_TOKEN/)
assert.match(assetBuild, /AppIcon-512@2x\.png/)
assert.match(assetBuild, /DarkBackground/)

console.log('native mobile build contract tests passed')
